import express from 'express';
import bcrypt from 'bcrypt';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const router = express.Router();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONFIG_PATH = path.join(__dirname, '..', 'config', 'installation.json');

// Check if setup is complete
router.get('/status', (req, res) => {
    try {
        if (fs.existsSync(CONFIG_PATH)) {
            const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
            res.json({
                setupComplete: true,
                organization: config.organization?.name || 'UrbanMIS'
            });
        } else {
            res.json({ setupComplete: false });
        }
    } catch (error) {
        res.json({ setupComplete: false });
    }
});

// Test database connection
router.post('/test-db', async (req, res) => {
    const { host, port, database, user, password } = req.body;

    try {
        const pg = await import('pg');
        const client = new pg.default.Client({
            host,
            port: parseInt(port),
            database,
            user,
            password,
            connectionTimeoutMillis: 5000
        });

        await client.connect();
        await client.query('SELECT 1');
        await client.end();

        res.json({ success: true, message: 'Connection successful' });
    } catch (error) {
        res.status(400).json({
            success: false,
            error: error.message || 'Connection failed'
        });
    }
});

// Initialize the system
router.post('/initialize', async (req, res) => {
    const { database, admin, organization, terminology } = req.body;

    try {
        // Validate required fields
        if (!database?.user || !database?.password || !admin?.email || !admin?.password) {
            return res.status(400).json({ error: 'Missing required fields' });
        }

        // Test database connection first
        const pg = await import('pg');
        const client = new pg.default.Client({
            host: database.host,
            port: parseInt(database.port),
            database: database.name,
            user: database.user,
            password: database.password
        });

        await client.connect();

        // Run schema if tables don't exist
        const tableCheck = await client.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'users'
            )
        `);

        if (!tableCheck.rows[0].exists) {
            const schemaPath = path.join(__dirname, '..', '..', 'database', 'schema.sql');
            if (fs.existsSync(schemaPath)) {
                const schema = fs.readFileSync(schemaPath, 'utf8');
                await client.query(schema);
            }
        }

        // Create or update admin user
        const passwordHash = await bcrypt.hash(admin.password, 10);

        await client.query(`
            INSERT INTO users (username, email, password_hash, first_name, last_name, role)
            VALUES ($1, $2, $3, $4, $5, 'admin')
            ON CONFLICT (username) DO UPDATE SET
                email = EXCLUDED.email,
                password_hash = EXCLUDED.password_hash,
                first_name = EXCLUDED.first_name,
                last_name = EXCLUDED.last_name
        `, [admin.username, admin.email, passwordHash, admin.firstName, admin.lastName]);

        await client.end();

        // Save configuration
        const config = {
            database: {
                host: database.host,
                port: database.port,
                name: database.name,
                user: database.user
                // Password not stored in config for security
            },
            organization: {
                name: organization?.name || 'UrbanMIS',
                primaryColor: organization?.primaryColor || '#4F46E5',
                logo: null
            },
            terminology: {
                client: terminology?.client || 'Client',
                worker: terminology?.worker || 'Worker',
                visit: terminology?.visit || 'Visit'
            },
            installedAt: new Date().toISOString()
        };

        // Ensure config directory exists
        const configDir = path.dirname(CONFIG_PATH);
        if (!fs.existsSync(configDir)) {
            fs.mkdirSync(configDir, { recursive: true });
        }

        fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));

        // Also write .env file
        const envContent = `# UrbanMIS Configuration
# Generated by setup wizard

NODE_ENV=production
PORT=3001

DB_HOST=${database.host}
DB_PORT=${database.port}
DB_NAME=${database.name}
DB_USER=${database.user}
DB_PASSWORD=${database.password}

JWT_SECRET=${generateSecureSecret()}
`;

        fs.writeFileSync(path.join(__dirname, '..', '.env'), envContent);

        res.json({ success: true, message: 'Setup complete' });
    } catch (error) {
        console.error('Setup error:', error);
        res.status(500).json({ error: error.message || 'Setup failed' });
    }
});

function generateSecureSecret() {
    return crypto.randomBytes(32).toString('hex');
}

export default router;
